dist: bionic
language: c
cache:
- pip
- ccache
env:
  global:
  - secure: tdQoakwaYJcfmRX1nI3kQgR4I7xjP3PYSHaQ9FZBUF5N5O5fJlgns5WF2ofh5WhvjuTKABMGBGqjNC9R7E68L24UCS2JftGHVQ0UQANtDdf3fN3wsD4Ev4tOM27blNj77Ud5fx2xZQfASDdh0Mrrz3GtE/FaLGoN3g9X03vRYnrD+z8aXn/j8oIVej26sOmy5DZfKbhtRv57f9A5ek9yMFkRD6NEbaisbTxvoW7Qri+6h9Rf3M4P8izufDsBBGj/eEoEOPfL5oDVJDOpy+cixAmaCc8GfGY5Kqd3pH8aBflaigdE0UOVUGD5EHQaHmth3P5Wzqz+tqVaGhNfhTh+blOlI1JId7ovEJPYnFur+RzLFhABqYjlhm6smCpNIOow/Q8gXAnMXNFq5460vlrOvHB3d0z20Gsb7cZamZsv0Nf6MfoXJQd9DniF45rAIGUGDFojg9xqVLuxzuMcTTTOaaSxYZ9g8pTDOFwwF5oCQLQ7gdeagv1EjexD3N3RhYQ/rR6TfbWbY98OhncDL4OYR5s48Nw+j747OVnp8N87S1R+AYWwgEDxRYFo8ykqsAPOzZCFazS+rXp4X9yA9VtgG0fWgpUh7cVeB9J0aZIps7yFu4oyFqltsRIcv6KgwtGukxVgnhT6RCMZGXazLorafJpDDwWjD+Ba66uyHwjVIhw=
  - secure: qFwNrx16rhlX5KKpkIfcgfwjlKXO1LtjN1uK5h+mp4ZnrFHiitCJl6wct2ZwKtBEc0V4ux57ZdggE9uff0Ur0ZAwal5QkQSpBToO99Gpk8S2TB4OFQq5wbD1EDzsqOY72FM28LUqejDqzaN7AwkRCKjvDFMvRiVrXtXF8iZqkaIz2Gv9DWEMYcXFbAhsqN7cRTnHlpgT4CNWjw0x7NW6CUUVoEwE4NaltED/QJhO4xI8IVTW1VPCnbwkHmvlSvjoqDgjCYyQLRD7MnhmKZQuY18iKYzHce2lLUcq9i76aJmnLfLUV61C4R1W1r+wQqXqs+wCkDFGzTRP3eq3P0Wx8hq55yUNQEojTIWrYAUdMLKHd+KxwDs94XiEXTslkur8C2BvrHr0NRIGuqr2kEzr6zRIlcf2bRvQLo/rsDPbzLpBGkePKy4vMLo7xUF70ztM9gvBsWjk5+bzxb8HQTiCCc1BnEUNEaKHXZxve93uGqGijfzwGFqaIyP2iWvUv6nWAq2bEhyS2QAe22nwk6PgIE3EB/hmfCcyzdszedLKJCrpYOrtZ8ucMcVuP4m8DVO9uCG7qsluSoA8E8RkP49gWpZ8YJ7syBuoBua/+68LJn3g/oWy3SlBawjqL0Cj1eRXcDrk4DWurZKiL7vQN4Mgq4rfE3yuBs9PQ3EKK+GZSkI=
  - secure: Pr0/hlroT/QMilFDmUoKvmZ61g5/DY9lGLaNX5EccxCYqiC373Zgi/gbN9OyRjJs9g93UZDW5lFJ3MGt2eBWeIbHeE37W+eTYp+2j0cb7PB0Iz604TDr+Rl8LQcAm6FqAqCNwq/OXuuHluZdvqKCmQPRhvAxREwOBM/P2UPsD45OqQGPSuSwyF67Fy3804cQI/hTffd+wRJCwEfCBKyPSLYY7NggvN+Vref6u8YlhcpFd0YJnGWNDgCOYJg9xqytJ+J7J3MBx1KAXpi992dlOdSQt6Y6V0Za+1MHI8xvhx4hXlDNlagqGDHgBLY2AwMtU5Worl4wUEkJXqYsxqL1wHrvLV+MHs1oJZug3LQ2U4Ntl/VZ7S0e243qMOR8hRaqK+6Hql+Cjm921YlU3cKXeX6OaDkqCuEORWCu6MyFSUfA56p+QOlG3raRMe9h2WqBwzQyqyoLm0bEY2g1WYDuiuUE6uB8Kos/VTZ+f/k0AJyortRzGGOrPphphTUq6VD9hkeCPzRcmIfTGbKwoWIUq8JSOvScUpT3rrTuXs7O2pFrgYVnOz6ewYtiJLkG5TjJ21r0wVrdoHhk96CoZP18cCtyU0HReolTj0lgs6n0s/SSQEy41249TkoiRo2jvmhPjsWsaDX1AtRAHMI8gGSS+F4QJeRH2z/XUlGs65eE3XU=
addons:
  apt:
    packages:
    - cmake
    - python3
    - python3-pip
    - python3-setuptools
    - python3-dev
    - libevent-2.1-6
    - libevent-dev
    - libsodium23
    - libsodium-dev
compiler:
- gcc
before_install: pip3 install --upgrade --user travis pip setuptools wheel virtualenv
install: pip3 install --user -r rpctest/requirements.txt
before_script:
- "./travis-build.sh"
script:
- "./nspv ILN &"
- sleep 10
- cd rpctest
- python3 travis.py $PARAM1 $PARAM2 $PARAM3
- python3 -m pytest test_nspv.py
